title: Oliver Chang # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Runner, CS/Stats Major, and baseball nerd - but not necessarily in that order.
  <br></br>
  I am interested in neural networks, statistics, and robotics. I like using R and Python for statistical analysis 
  and Java for software engineering. 
  <br></br>
  I am currently a senior at Pomona college, studying computer science and math. Outside of school,
  I run cross country and track & field, work as a CS RA, and watch Dodger baseball. 
  <br></br>
  Feel free to checkout my <a href="pdf/EliasOliverChang_resume.pdf">resume</a> and my 
  <a href="pdf/fall_transcript2020.pdf">transcript</a>.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
